//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSoutenanceBack.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int id { get; set; }
        public string titre { get; set; }
        public string contenu { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<int> users_id { get; set; }
        public Nullable<int> article_id { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Users Users { get; set; }
    }
}
